colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'
  # Normal colors
  #normal:
  #  black:   '#000000'
  #  red:     '#d54e53'
  #  green:   '#b9ca4a'
  #  yellow:  '#e6c547'
  #  blue:    '#7aa6da'
  #  magenta: '#c397d8'
  #  cyan:    '#70c0ba'
  #  white:   '#eaeaea'

  # Bright colors
  #bright:
  #  black:   '#666666'
  #  red:     '#ff3334'
  #  green:   '#9ec400'
  #  yellow:  '#e7c547'
  #  blue:    '#7aa6da'
  #  magenta: '#b77ee0'
  #  cyan:    '#54ced6'
  #  white:   '#ffffff'

  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  #dim:
  #  black:   '#000000'
  #  red:     '#8c3336'
  #  green:   '#7a8530'
  #  yellow:  '#97822e'
  #  blue:    '#506d8f'
  #  magenta: '#80638e'
  #  cyan:    '#497e7a'
  #  white:   '#9a9a9a'
